language: node_js

node_js:
  - "10"
  - "12"

stages:
  - test

jobs:
  - include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Test start..."
        - npm run test
        - echo "Test end!!!"
